name: ShazamScrobbler
title: ShazamScrobbler for Mac

app:
 os: "OS X 10.9+"
 shazam-version: "1.1.1"
 current: "1.1"

images:
 icon:
 favicon:

social:
 twitter: shazamscrobbler
 github: shazamscrobbler
 facebook: shazamscrobbler

owner:
 name: Stéphane Bruckert
 website: http://stephanebruckert.com
 github: stephanebruckert

collections:
 md-faq:
  output: true
 md-usecases:
  output: true