name: ShazamScrobbler
short-description: Scrobble vinyl, radios, movies to Last.fm
long-description: Menubar app for people who use Shazam to identify songs played on or around their Mac and who would like to keep an updated playback history using Last.fm's scrobbling service.
title: ShazamScrobbler for Mac
keywords: scrobble, shazam, mac, menubar, app, vinyl, radio, movies, ost, apple music, lastfm, audioscrobbler
year: 2021

app:
 os: "OS X 10.9+"
 shazam-version: "2.10.0"
 current: "1.3.0"

images:
 icon:
 favicon:

social:
 twitter: shazamscrobbler
 github: shazamscrobbler
 facebook: shazamscrobbler

owner:
 name: Stéphane Bruckert
 website: http://stephanebruckert.com

collections:
 md-faq:
  output: true
 md-usecases:
  output: true
